In [1]:
import numpy as np

In [ ]:
#CREACION Y INDEXACION 

In [ ]:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5. -- MAL ENTENDIDO 
a1d = np.random.randint(10, 100, (5,4))

In [5]:
a1d

array([[97, 82, 40, 39],
       [92, 14, 47, 41],
       [33, 58, 75, 23],
       [42, 82, 56, 44],
       [44, 35, 91, 26]], dtype=int32)

In [ ]:
condicion = a1d % 5 == 0 

print(condicion)

[[False False  True False]
 [False False False False]
 [False False  True False]
 [False False False False]
 [False  True False False]]


In [11]:
a1d[condicion]

array([40, 75, 35], dtype=int32)

In [7]:
if True == True:
    print(a1d.shape)

(5, 4)


In [ ]:
lista_multiplos = []

for n in a1d.flatten():
    if (n%5 == 0):
        lista_multiplos.append(n)

print(lista_multiplos)

[np.int32(40), np.int32(75), np.int32(35)]


In [12]:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5. -- BIEN ENTENDIDO 
array_1d = np.random.randint(10, 100, 50)

In [13]:
print(array_1d)

[53 75 80 40 27 45 23 18 28 28 52 74 78 95 29 31 46 82 56 97 50 82 52 38
 52 69 88 15 84 27 37 97 80 49 23 97 99 49 59 40 48 42 65 90 88 49 40 71
 28 16]


In [14]:
array_1d[::5]

array([53, 45, 52, 31, 50, 69, 37, 97, 48, 49], dtype=int32)

In [15]:
#Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.
array_1d2 = np.random.randint(1, 21, 30)

In [16]:
print(array_1d2)

[10 16  2 12  7 18  7 11  1 11  9 15 11  9  9  4 15  1  1  3  4  6  4  4
 16 19  8 15  6 14]


In [18]:
array_1d2[1::2]

array([16, 12, 18, 11, 11, 15,  9,  4,  1,  3,  6,  4, 19, 15, 14],
      dtype=int32)

In [ ]:
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. 
#Los decimales deben estar redondeados a 2 decimales.

In [25]:
a = np.random.randint(1, 99, (4,6))

In [26]:
b = np.random.rand(4,6)

In [27]:
c = np.random.randint(1, 99, (4,6)) + np.random.rand(4,6)

In [28]:
print(c)

[[33.42089266 52.65070408 46.23710527 13.55608684 51.88813056 49.88117191]
 [11.82679237 63.56216306 84.0102087  36.23786607 78.23772826 83.73899859]
 [50.15111257 18.19133083 44.72757536 73.32172864 11.13529093 54.99503884]
 [69.8820526  17.61078407 50.44236418 66.04778735 55.4837619  83.93143016]]


In [31]:
c = np.round(c, 2)

In [32]:
c [-1]

array([69.88, 17.61, 50.44, 66.05, 55.48, 83.93])

In [19]:
a = 3
b = 0.7
a + b

3.7

In [34]:
#Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.
a_3d = np.random.rand(2,3,5)

In [35]:
a_3d = np.round(a_3d, 1)

In [36]:
a_3d

array([[[0.7, 0.8, 0.2, 0.6, 0.1],
        [0.1, 0.3, 0.7, 0.5, 0.9],
        [0.8, 0. , 1. , 1. , 0.2]],

       [[0.5, 0.6, 0.7, 0.7, 0.4],
        [0.1, 0.4, 0.6, 0.4, 0.7],
        [1. , 0. , 0.7, 0.7, 0.6]]])

In [40]:
#Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 
#Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones

a_d2 = np.empty((2,3,5))

In [61]:
a_d2

array([[[0.7, 0.8, 0.2, 0.6, 0.1],
        [0.1, 0.3, 0.7, 0.5, 0.9],
        [0.8, 0. , 1. , 1. , 0.2]],

       [[0.5, 0.6, 0.7, 0.7, 0.4],
        [0.1, 0.4, 0.6, 0.4, 0.7],
        [1. , 0. , 0.7, 0.7, 0.6]]])

In [54]:
#Si el valor del array es igual que la media, se reemplaza por "A".
media1 = np.mean(a_d2)
print(media)

0.5333333333333333


In [55]:
suma = np.sum(a_d2)
print(suma)

15.999999999999998


In [56]:
np.where(media1 == suma, "A")

ValueError: either both or neither of x and y should be given

In [63]:
rw = np.where(a_d2 > 0.53, "A", a_d2)

In [64]:
print(rw)

[[['A' 'A' '0.2' 'A' '0.1']
  ['0.1' '0.3' 'A' '0.5' 'A']
  ['A' '0.0' 'A' 'A' '0.2']]

 [['0.5' 'A' 'A' 'A' '0.4']
  ['0.1' '0.4' 'A' '0.4' 'A']
  ['A' '0.0' 'A' 'A' 'A']]]
